# Project 2

##### Imports

In [1]:
import pandas as pd
import numpy as np
import kagglehub

c:\Users\fbase\All_vscode_projects\envs\ml-env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

##### 1. Run this section to load dataset

$$\huge \texttt{Data loading}$$

In [2]:
# Run this once for downloading the dataset
#url = "https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$limit=200000"
#df = pd.read_csv(url)

#df.to_csv("nyc_311_sample.csv", index=False)

In [3]:
df = pd.read_csv("nyc_311_sample.csv")
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.601042,-73.979387,POINT (-73.979387264647 40.601042365906)
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.743346,-73.886114,POINT (-73.886113509027 40.74334566695)
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
clean_status = pd.DataFrame([],columns=df.columns)
clean_status[df.columns] = np.full((1,44),False)

In [70]:
clean_status

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

##### 2. Take a peek at your dataset

$$\huge \texttt{Data overview}$$

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 44 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   unique_key                      200000 non-null  int64
 1   created_date                    200000 non-null  str
 2   closed_date                     158957 non-null  str
 3   agency                          200000 non-null  str
 4   agency_name                     200000 non-null  str
 5   complaint_type                  200000 non-null  str
 6   descriptor                      197180 non-null  str
 7   descriptor_2                    74933 non-null   str
 8   location_type                   162834 non-null  str
 9   incident_zip                    197358 non-null  float64
 10  incident_address                187723 non-null  str
 11  street_name                     187719 non-null  str
 12  cross_street_1                  136270 non-null  str
 13  cross_street_2                  136295 non-null  str
 14  intersection_street_1           127389 non-null  str
 15  intersection_street_2           127471 non-null  str
 16  address_type                    198295 non-null  str
 17  city                            189374 non-null  str
 18  landmark                        108403 non-null  str
 19  facility_type                   654 non-null     str
 20  status                          200000 non-null  str
 21  due_date                        746 non-null     str
 22  resolution_description          186218 non-null  str
 23  resolution_action_updated_date  187820 non-null  str
 24  community_board                 200000 non-null  str
 25  council_district                188316 non-null  float64
 26  police_precinct                 200000 non-null  str
 27  bbl                             166192 non-null  float64
 28  borough                         200000 non-null  str
 29  x_coordinate_state_plane        189407 non-null  float64
 30  y_coordinate_state_plane        189425 non-null  float64
 31  open_data_channel_type          200000 non-null  str
 32  park_facility_name              199888 non-null  str
 33  park_borough                    200000 non-null  str
 34  vehicle_type                    9530 non-null    str
 35  taxi_company_borough            152 non-null     str
 36  taxi_pick_up_location           2040 non-null    str
 37  bridge_highway_name             1643 non-null    str
 38  bridge_highway_direction        1215 non-null    str
 39  road_ramp                       1174 non-null    str
 40  bridge_highway_segment          1640 non-null    str
 41  latitude                        189398 non-null  float64
 42  longitude                       189398 non-null  float64
 43  location                        189398 non-null  str
dtypes: float64(7), int64(1), str(36)
memory usage: 67.1 MB

In [5]:
df.isna().sum()

unique_key                             0
created_date                           0
closed_date                        41043
agency                                 0
agency_name                            0
complaint_type                         0
descriptor                          2820
descriptor_2                      125067
location_type                      37166
incident_zip                        2642
incident_address                   12277
street_name                        12281
cross_street_1                     63730
cross_street_2                     63705
intersection_street_1              72611
intersection_street_2              72529
address_type                        1705
city                               10626
landmark                           91597
facility_type                     199346
status                                 0
due_date                          199254
resolution_description             13782
resolution_action_updated_date     12180
community_board                        0
council_district                   11684
police_precinct                        0
bbl                                33808
borough                                0
x_coordinate_state_plane           10593
y_coordinate_state_plane           10575
open_data_channel_type                 0
park_facility_name                   112
park_borough                           0
vehicle_type                      190470
taxi_company_borough              199848
taxi_pick_up_location             197960
bridge_highway_name               198357
bridge_highway_direction          198785
road_ramp                         198826
bridge_highway_segment            198360
latitude                           10602
longitude                          10602
location                           10602
dtype: int64

In [6]:
"""
for i in range(1,5):
    try:
        display(df.iloc[:,i:i*10].head())
    except:
        display(df.iloc[:,i*10:].head())
"""
#Looking at few columns makes it easier
subset1 = df.iloc[:,:11].head()
subset1

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,65 ROAD
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,CONVENT AVENUE
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,NaN
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,42-71 79 STREET
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,43 STREET

In [7]:
subset2 = df.iloc[:,11:21].head()
subset2

,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status
0,65 ROAD,POWER ROAD,102 STREET,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Open
1,CONVENT AVENUE,WEST 133 STREET,WEST 135 STREET,NaN,NaN,BLOCKFACE,MANHATTAN,NaN,NaN,Open
2,NaN,NaN,NaN,AVENUE S,WEST 7 STREET,INTERSECTION,BROOKLYN,NaN,NaN,Open
3,79 STREET,WOODSIDE AVENUE,45 AVENUE,NaN,NaN,ADDRESS,ELMHURST,NaN,NaN,Closed
4,43 STREET,35 AVENUE,NORTHERN BOULEVARD,NaN,NaN,BLOCKFACE,QUEENS,NaN,NaN,Open

In [8]:
subset3 = df.iloc[:,21:31].head()
subset3

,due_date,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane
0,NaN,The Department of Transportation referred this...,2026-03-31T02:39:38.000,Unspecified QUEENS,NaN,Unspecified,NaN,QUEENS,NaN,NaN
1,NaN,The Department of Transportation referred this...,2026-03-31T02:30:56.000,09 MANHATTAN,NaN,Precinct 26,NaN,MANHATTAN,NaN,NaN
2,NaN,The Department of Transportation referred this...,2026-03-31T02:26:57.000,11 BROOKLYN,43.0,Precinct 62,NaN,BROOKLYN,989974.0,158253.0
3,NaN,DSNY already has a request to investigate this...,2026-03-31T12:00:00.000,04 QUEENS,25.0,Precinct 110,4.015250e+09,QUEENS,1015808.0,210118.0
4,NaN,The Department of Transportation referred this...,2026-03-31T02:17:11.000,01 QUEENS,NaN,Precinct 114,NaN,QUEENS,NaN,NaN

In [9]:
subset4 = df.iloc[:,31:41].head()
subset4

,open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UNKNOWN,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### 3. Cleaning

$$\huge \texttt{Data Cleaning}$$

###### Things I could do next time
1. Evaluate where we can remove NaN from
2. Seperate time from datetime columns
3. Evaluate the values of all columns do they all make sense or is there corrupted data

In [10]:
subset1.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,65 ROAD
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,CONVENT AVENUE
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,NaN
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,42-71 79 STREET
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,43 STREET

Columns : Reason why null values appear
Closed dates : Because those service records have not been resolved?
>Does a service request being closed always mean that it has been resolved ( yes , no cause of something else , no without any reason )

In [11]:
"""
Q1 = [['question','answer']]
print("Try to answer in one line if possible")
for i in df.columns:
    question = f"How could {i} be the reason for closing a Service request?"
    print(question)
    answer = input(" Answer :")
    Q1.append([question,answer])

td = pd.DataFrame(Q1)
td.to_csv("Inventory.csv",columns=['question','answer'])
"""

'\nQ1 = [[\'question\',\'answer\']]\nprint("Try to answer in one line if possible")\nfor i in df.columns:\n    question = f"How could {i} be the reason for closing a Service request?"\n    print(question)\n    answer = input(" Answer :")\n    Q1.append([question,answer])\n\ntd = pd.DataFrame(Q1)\ntd.to_csv("Inventory.csv",columns=[\'question\',\'answer\'])\n'

1. A specific location/region could be the reason for closing or request
2. A specific type of problem could be the description for closing a request
3. A specific entity could be the reason for closing a request ( The work well so close more SR )

In [12]:
df['status'].unique()

<StringArray>
[       'Open',      'Closed', 'In Progress',    'Assigned',     'Started',
     'Pending', 'Unspecified']
Length: 7, dtype: str

In [13]:
cond1 = [df['closed_date'].notna(),df['closed_date'].isna()]
cd = ['not_null',np.nan]
ts = []
for i in range(2):
    for j in df['status'].unique():
        td = df[cond1[i]]
        try:
            td[td['status']==j].iloc[0]
            ts.append([cd[i],j])
        except:
            pass
            ts.append([cd[i],np.nan])

closed_date_x_status = pd.DataFrame(ts,columns=['closed_date','status'])
closed_date_x_status

   closed_date       status
0     not_null         Open
1     not_null       Closed
2     not_null          NaN
3     not_null     Assigned
4     not_null      Started
5     not_null      Pending
6     not_null  Unspecified
7          NaN         Open
8          NaN          NaN
9          NaN  In Progress
10         NaN     Assigned
11         NaN      Started
12         NaN      Pending
13         NaN  Unspecified

In [ ]:
notnull_closed_dates = df[df['closed_date'].notna()]['closed_date']
pattern = r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d+\.\d+$"
notnull_closed_dates.str.match(pattern).unique()

array([ True])

In [ ]:
notnull_closed_dates.shape[0] + df[df['closed_date'].isna()].shape[0]
# This proves that except for the NaN ,  closed date has all valid string which follow this pattern (no rubbish value like unknown etc )

200000

In [33]:
notnull_closed_dates[notnull_closed_dates.duplicated(keep=False)]

75        2026-03-31T02:01:26.000
109       2026-03-31T01:54:57.000
159       2026-03-31T01:00:21.000
201       2026-03-31T01:54:57.000
203       2026-03-31T01:29:50.000
                   ...
199965    2026-03-30T19:37:43.000
199973    2026-03-14T15:54:00.000
199983    2026-03-13T00:00:00.000
199985    2026-03-12T12:59:01.000
199999    2026-03-13T08:56:36.000
Name: closed_date, Length: 51306, dtype: str

In [ ]:
value = '2026-03-31T02:01:26.000'
notnull_closed_dates[notnull_closed_dates.str.match(value)]
# Okay there are some duplicated values , is this possible?

75      2026-03-31T02:01:26.000
1796    2026-03-31T02:01:26.000
Name: closed_date, dtype: str

In [ ]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None):
    display(df.iloc[[75,1796],:])
# Okay two entries can be closed at the same time , sounds rare but its possible

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane,open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
75,68504007,2026-03-31T01:23:55.000,2026-03-31T02:01:26.000,NYPD,New York City Police Department,Noise - Commercial,Loud Talking,NaN,Club/Bar/Restaurant,11216.0,299 HALSEY STREET,HALSEY STREET,TOMPKINS AVENUE,THROOP AVENUE,TOMPKINS AVENUE,THROOP AVENUE,ADDRESS,BROOKLYN,HALSEY STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-03-31T02:01:12.000,03 BROOKLYN,36.0,Precinct 79,3.018400e+09,BROOKLYN,1000520.0,188042.0,ONLINE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.682794,-73.941338,POINT (-73.94133816146 40.682793665961)
1796,68511460,2026-03-30T21:09:03.000,2026-03-31T02:01:26.000,NYPD,New York City Police Department,Illegal Parking,Blocked Crosswalk,NaN,Street/Sidewalk,11219.0,42 STREET,42 STREET,42 STREET,10 AVENUE,42 STREET,10 AVENUE,INTERSECTION,NaN,NaN,NaN,Closed,NaN,The New York City Police Department responded ...,2026-03-31T02:01:21.000,12 BROOKLYN,38.0,Precinct 66,NaN,BROOKLYN,985737.0,173516.0,ONLINE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642938,-73.994642,POINT (-73.994641792031 40.642937837713)

In [ ]:
print(df.duplicated().unique())
print(df.unique_key.duplicated().unique())
# No duplicate rows / entries

[False]
[False]

`closed_date` is completely clean

In [51]:
# Now are all these combinations of closed_data and status possible?
closed_date_x_status['Possible?'] = [0,1,1,0,0,0,1,1,0,1,1,1,1,0]
closed_date_x_status['Possible?'] = closed_date_x_status['Possible?'].astype('bool')
closed_date_x_status['description'] = ["Human error","Possible","Human error","Human error","Human error",
                                       "Human error","Human error","Possible","Human error","Possible",
                                       "Possible","Possible","Possible","Human error"]
closed_date_x_status
# This will be useful when we are using status column as our feature

   closed_date       status  Possible?  description
0     not_null         Open      False  Human error
1     not_null       Closed       True     Possible
2     not_null          NaN       True  Human error
3     not_null     Assigned      False  Human error
4     not_null      Started      False  Human error
5     not_null      Pending      False  Human error
6     not_null  Unspecified       True  Human error
7          NaN         Open       True     Possible
8          NaN          NaN      False  Human error
9          NaN  In Progress       True     Possible
10         NaN     Assigned       True     Possible
11         NaN      Started       True     Possible
12         NaN      Pending       True     Possible
13         NaN  Unspecified      False  Human error

In [ ]:
#  1 means clean
#  2 means not clean
#  3 means that its not clean but I know which ones are not clean
#  Boolean values mean , I haven't gone through them
clean_status[['unique_key','closed_date','status']] = [1,1,3]

In [ ]:
print(df[df['created_date'].isna()].size)
# There are no null values in created_date

pattern = r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d+\.\d+$"


print(df['created_date'].str.match(pattern).unique()) # gives a boolean array where the pattern matches, False implies there are values which don't match this pattern , True implies there are values which match this pattern

print("No of duplicated values :",df['created_date'][df['created_date'].duplicated(keep=False)].size)
print("Total values : ",df['created_date'].shape[0])

0
[ True]
No of duplicated values : 55830
Total values :  200000

In [89]:
clean_status['created_date'] = 1

In [98]:
subset1

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,65 ROAD
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,CONVENT AVENUE
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,NaN
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,42-71 79 STREET
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,43 STREET

In [122]:
b = {k:df.iloc[:,k].unique() for k in [3,4,5]}
for k,v in b.items():
    print(k)
    print(v,'\n')

3
<StringArray>
[  'DOT',  'DSNY',  'NYPD',   'DHS',  'DCWP',   'OOS',   'OTI', 'DOHMH',
   'TLC',   'DPR',   'HPD',   'DEP',   'EDC',   'DOB',   'DOE']
Length: 15, dtype: str

4
<StringArray>
[                      'Department of Transportation',
                           'Department of Sanitation',
                    'New York City Police Department',
                    'Department of Homeless Services',
       'Department of Consumer and Worker Protection',
                              'Office of the Sheriff',
                'Office of Technology and Innovation',
            'Department of Health and Mental Hygiene',
                      'Taxi and Limousine Commission',
                 'Department of Parks and Recreation',
 'Department of Housing Preservation and Development',
             'Department of Environmental Protection',
                   'Economic Development Corporation',
                            'Department of Buildings',
                            'Department of Education']
Length: 15, dtype: str

5
<StringArray>
[          'Street Condition',          'Derelict Vehicles',
            'Illegal Parking',    'Noise - Street/Sidewalk',
                    'Traffic',        'Noise - Residential',
              'Drug Activity',            'Noise - Vehicle',
           'Blocked Driveway',            'Dirty Condition',
 ...
            'Trapping Pigeon',     'Highway Sign - Damaged',
         'School Maintenance',             'Found Property',
 'Municipal Parking Facility',                'Snow or Ice',
                 'Poison Ivy',    'Highway Sign - Dangling',
      'DEP Highway Condition',        'Cranes and Derricks']
Length: 166, dtype: str

In [123]:
for i in b[5]:
    print(i)

Street Condition
Derelict Vehicles
Illegal Parking
Noise - Street/Sidewalk
Traffic
Noise - Residential
Drug Activity
Noise - Vehicle
Blocked Driveway
Dirty Condition
Homeless Person Assistance
Consumer Complaint
Non-Emergency Police Matter
Noise - Park
Noise - Commercial
Cannabis Retailer
Urinating in Public
LinkNYC
Smoking or Vaping
Lost Property
Indoor Air Quality
Graffiti
Litter Basket Request
Curb Condition
Missed Collection
Encampment
Illegal Dumping
Abandoned Vehicle
Animal-Abuse
Drinking
Rodent
Street Light Condition
Street Sign - Damaged
Food Establishment
Vendor Enforcement
Illegal Tree Damage
Abandoned Bike
Damaged Tree
Panhandling
Illegal Posting
Obstruction
GENERAL
For Hire Vehicle Complaint
Noise
UNSANITARY CONDITION
PLUMBING
SAFETY
HEAT/HOT WATER
Outdoor Dining
Traffic Signal Condition
Dead Animal
Sewer
ELECTRIC
Water System
Noise - Helicopter
Food Poisoning
WATER LEAK
Lead
Illegal Fireworks
FLOORING/STAIRS
Hazardous Materials
Overgrown Tree/Branches
Sidewalk Condition
DOOR/WINDOW
Taxi Complaint
Air Quality
PAINT/PLASTER
Asbestos
Dumpster Complaint
Highway Condition
Residential Disposal Complaint
Root/Sewer/Sidewalk Condition
Maintenance or Facility
OUTSIDE BUILDING
Animal in a Park
ELEVATOR
Sanitation Worker or Vehicle Complaint
Bike/Roller/Skate
Water Conservation
Elevator
Indoor Sewage
New Tree Request
General Construction/Plumbing
Street Sweeping Complaint
Building/Use
Street Sign - Dangling
APPLIANCE
Taxi Report
Bus Stop Shelter Complaint
Plumbing
Electrical
Commercial Disposal Complaint
Special Projects Inspection Team (SPIT)
Uprooted Stump
Street Sign - Missing
Ferry Inquiry
Dead/Dying Tree
Mobile Food Vendor
Day Care
Unsanitary Pigeon Condition
Disorderly Youth
Unsanitary Animal Pvt Property
Broken Parking Meter
Emergency Response Team (ERT)
Boilers
Wood Pile Remaining
Real Time Enforcement
Lot Condition
Litter Basket Complaint
Violation of Park Rules
Bike Rack
Unleashed Dog
Bench
Drinking Water
Noise - House of Worship
Green Taxi Complaint
Construction Lead Dust
BEST/Site Safety
Bridge Condition
Public Toilet
Investigations and Discipline (IAD)
Industrial Waste
Scaffold Safety
Mold
Special Natural Area District (SNAD)
Harboring Bees/Wasps
Water Quality
Recycling Basket Complaint
Institution Disposal Complaint
For Hire Vehicle Report
E-Scooter
Beach/Pool/Sauna Complaint
Safety
Building Drinking Water Tank
Illegal Animal Kept as Pet
Illegal Animal Sold
Unsanitary Animal Facility
Non-Residential Heat
Lifeguard
Pet Sale
Ferry Complaint
Squeegee
Oil or Gas Spill
Tobacco or Non-Tobacco Sale
AHV Inspection Unit
Posting Advertisement
Tattooing
Animal Facility - No Permit
Highway Sign - Missing
Taxi Compliment
Bus Stop Shelter Placement
FHV Licensee Complaint
Cooling Tower
Incorrect Data
Plant
Dept of Investigations
Trapping Pigeon
Highway Sign - Damaged
School Maintenance
Found Property
Municipal Parking Facility
Snow or Ice
Poison Ivy
Highway Sign - Dangling
DEP Highway Condition
Cranes and Derricks

In [124]:
# agency , agency_name , complaint_type all have no null values
# After looking at their unique values , I can safely say that there are no corrupted values
clean_status[['agency','agency_name','complaint_type']] = [1,1,1]

In [ ]:
# Interpret this results which one of these is actually possible?

In [ ]:
#workflow of how a record is added and when is it confirmed

#### Hide

##### 4. EDA

$$\huge \texttt{Exploratory data analysis}$$

In [ ]:
# Columns that I think might affect Response time
claim = [{'refers to the same agency':['agency','agency']},
         'complaint_type',
         'due_date',
         'resolution_description',
         'resolution_action_updated_date',
         'open_data_channel_type',
         {'description of problem':['descriptor','descriptor_2']},
         {'location':   ['location_type','incident_zip','incident_address', 'street_name', 'cross_street_1', 'cross_street_2',
                            'intersection_street_1', 'intersection_street_2','address_type','city', 'landmark', 'facility_type',
                            'community_board', 'council_district','police_precinct', 'bbl', 'borough', 'x_coordinate_state_plane',
                            'y_coordinate_state_plane','latitude', 'longitude', 'location'],
       'park_location': ['park_facility_name', 'park_borough'],
       'taxi_location': ['taxi_company_borough', 'taxi_pick_up_location'],
       'bridge_location': ['bridge_highway_name',
                            'bridge_highway_direction', 'road_ramp', 'bridge_highway_segment']},]

# Columns that I don't think affect the Response time
NotClaim = ['unique_key', 'created_date', 'closed_date','status']

##### 5. Data transformations

$$\huge \texttt{Data pre-processing}$$
$$\normalsize \texttt{In this section , We are gonna prepare our data for model input}$$

##### 6. Training

$$\huge \texttt{Model Training}$$
$$\normalsize \texttt{Training the model / trying out different things with the model and improving the result of desired metrics}$$

##### 7. evaluation

$$\huge \texttt{Model evaluation / interpretation}$$
$$\normalsize \texttt{We showcase and interpret the result here}$$